### ISSUE TITLE
Move CI/CD pipeline to Azure DevOps from AppVeyor

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#2286]
Move the test/CI/PR build functionality onto the same server as used for daily & release builds.

VSTS test build and reporting functionality is currently in preview.

Use the same infrastructure for builds of [Rapid XAML Toolkit](https://github.com/Microsoft/Rapid-XAML-Toolkit/issues/12)

> MEETING NOTES
> VSTS with CI/CD to remove appvayor
> *	Sync with Oren
> *	Get instance also for RXT

ActionPlan: 

- [x] Move CoreTS CI and PR builds
- [x] Move WinTS PR build to public AzureDevOps project
- [x] Move WinTS CI and Test builds to public AzureDevOps

**Comment by mrlacey** [comment]
@sibille I believe there was some progress on this. Can this issue be closed? or at least updated?

**Comment by sibille** [comment]
CoreTS PR & CI builds are running on Azure Devops, adding this to milestone 3.4 to do the same for WinTS builds

**Comment by sibille** [comment]
Added PR build to AzureDevOps (https://winappstudio.visualstudio.com/WTS/_build?definitionId=162).
It is currently running side by side with the Appveyor one to ensure there are no issues for anybody, before swapping over

**Comment by sibille** [comment]
Moving to milestone 3.6 to finish porting there

**Comment by sibille** [comment]
All test and ci builds are now running on AzureDevOps https://winappstudio.visualstudio.com/DefaultCollection/WTS
