### ISSUE TITLE
Keep telemetry data up to date

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2295]
Investigate improved tooling/processes to make it easier to keep the public [telemetry data](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/telemetryData.md) up to date.

Update with Action Plan:

- [x] Create Azure function
- [x] Create and configure SendGrid service
- [x] Create Telemetry queries and add to azure function
- [x] Create .md file with telemetry query results
- [x] Use SendGrid in Azure function to send .md file
- [x] Deploy azure function for dev
- [x] Test azure function in dev
- [x] Deploy azure function for pro

**Comment by sibille** [comment]
We were looking at this and think the best option is a azure function that sends a mail on 1st of every month with the TelemetryData.md filled with data from the previous month to review and do the PR.

**Comment by dgomezc** [comment]
In App Insight telemetry data, project and frameworks names differ from what is shown in the wizard (for example SplitView - Navigation View). For now we added a dictionary to map between the values to generate the telemetry data markdown file but we should add the display name to telemetry events in a new property and use those instead of the dictionary.

**Comment by sibille** [comment]
Configured and tested with production data. Regarding recording the displayname in telemetry events I think the current approach is better. Display names might change and we need a value that does not change for telemetry.
