### ISSUE TITLE
WinUI 3 Templates

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3807]
Create apps using **Windows UI Library 3 Preview 2** check [WinUI doc](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/) to know the required development setup.

**The mockup** is placed [Mockup-WinUI3 branch](https://github.com/microsoft/WindowsTemplateStudio/tree/Mockup-WinUI3/mockup/WinUI3).

**Specs**
 - WinUI Desktop App in C#
 - App packaged with MSIX
 - Use WinUI3 NavigationView as project type
 - Use Windows Community Toolkit [MVVM library](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3230) as design patern using Dependency Injection.
 - Use Windows Community Toolkit controls version 8.0.0-preview2 from [preview MyGet](https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json).

**Pages**
 - Blank page
 - ContentGrid page with AdaptativeGridView from WCT
 - DataGrid page with DataGrid from WCT
 - WebView page with WebView2 from WinUI3
 - Form page with Input Validation 
 - Setting page with Theme support (Dark, Light, Windows Default)

**Features**
 - ThemeSelection
 - SampleData
 - Settings Storage
 - Toast Notifications

**Roadmap**
- [ ] Create the mockup
- [ ] Get feedback and add enhancements
- [ ] Create templates
- [ ] Docs
- [ ] CI/CD integration

There are some issues on dev features or dev features that are not implemented yet and these are pending to be included in the mockup.

**WinUI Known Issues**

 - Localized string resources [2602](https://github.com/microsoft/microsoft-ui-xaml/issues/2602) available in Preview 3.
 - ToastNotification app lifecycle activation [111](https://github.com/microsoft/ProjectReunion/issues/111).

**Windows Community Toolkit Issues**
 - App crash on using MasterDetailView control [3433](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3433).

**Comment by mrlacey** [comment]
> Create apps using Windows UI Library 3 Preview 2 check WinUI doc to know the required development setup.

How have WinUI doc(s) been checked?

What knowledge has been gained of the required development setup? Is this documented anywhere?

---

Was this issue created to record that a mockup has been created or does it exist for any other specific purposes? If so, what are they?

---

"Create the mockup" is listed in the "next steps". How will this be different to what's in the referenced branch?

---

For the items in the list of Specs, pages, and features:
- Are these just lists of what is in the mockup branch?
- Are there plans for other items/options to be added in the future?
- Will these all eventually be individually selectable options in the wizard or are some required?

**Comment by mrlacey** [comment]
Has any consideration been given to reducing the coupling of ViewModels to views with these new templates? (X-Ref #2867)

I've noticed developers are increasingly putting their ViewModels in a .NET Standard library to enforce a reduced coupling of the ViewModel to the UI.

**Comment by mvegaca** [comment]
[This doc](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/) explains the setup that you should install in your PC to develop WinUI3 apps, this setup was used to create the mockup.

Create Mockup is in the list of next steps and it's no marked as completed because there are some open issues and things that need to implement before creating templates (i.e. localized string resources, master-detail page or toast notification).

I'm not sure or how this templates will be included in the wizard, by this moment we should be focused in the mockup, the code and the integration with WinUI3 and WCT.

**Comment by mvegaca** [comment]
The list of initial pages and features was created using the list of most used templates in UWP and WPF platforms.

**Comment by Javier118** [comment]
Win3UI will support Svg Icon in NavigationViewItem

**Comment by vmadurga** [comment]
Closing the issue in favor of #3810.
